coverage:
    status:
        project:
            default:
                # basic
                target: auto
                threshold: 0.5%
        patch:
            default:
                # basic
                target: auto
                threshold: 0.5%
